DOMAIN = "sabiana_energy_smart"
CONF_SLAVE = "slave"

# SENSOR_DEFINITIONS = [
#     {"name": "RVU Temp Probe 1", "address": 0x0100, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp1"},
#     {"name": "RVU Temp Probe 2", "address": 0x0101, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp2"},
#     {"name": "RVU Temp Probe 3", "address": 0x0102, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp3"},
#     {"name": "RVU Temp Probe 4", "address": 0x0103, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp4"},
#     {"name": "Fan 1 Speed RPM", "address": 0x010B, "unit": "rpm", "unique_id": "sabiana_sensor_fan1_speed_rpm"},
#     {"name": "Fan 2 Speed RPM", "address": 0x010C, "unit": "rpm", "unique_id": "sabiana_sensor_fan2_speed_rpm"},
#     {"name": "Fan 1 Duty %", "address": 0x010D, "unit": "%", "scale": 0.1, "precision": 1, "unique_id": "sabiana_sensor_fan1_speed_percent"},
#     {"name": "Fan 2 Duty %", "address": 0x010E, "unit": "%", "scale": 0.1, "precision": 1, "unique_id": "sabiana_sensor_fan2_speed_percent"},
#     {"name": "Preheater Duty %", "address": 0x010F, "unit": "%", "unique_id": "sabiana_sensor_preaheter_percent"},
#     {"name": "Humidity Setpoint", "address": 0x0106, "unit": "%", "scale": 0.1, "precision": 1, "device_class": "humidity", "unique_id": "sabiana_sensor_humidity_setpoin"},
#     {"name": "CO2 Level", "address": 0x0113, "unit": "ppm", "scale": 0.01, "precision": 2, "device_class": "carbon_dioxide", "unique_id": "sabiana_sensor_co2_level"},
#     {"name": "RVU Operating Mode", "address": 0x0119, "unique_id": "sabiana_sensor_operation_mode"},
#     {"name": "Party Mode Status", "address": 0x011A, "unique_id": "sabiana_sensor_partymode"},
#     {"name": "Filter Alarm", "address": 0x0107, "unique_id": "sabiana_sensor_filter_alarm"},
# ]

SENSOR_DEFINITIONS_NEW = {
    0x0100: {
        "key": "probe_temp1",
        "name": "RVU Temp Probe 1",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0101: {
        "key": "probe_temp2",
        "name": "RVU Temp Probe 2",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0102: {
        "key": "probe_temp3",
        "name": "RVU Temp Probe 3",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0103: {
        "key": "probe_temp4",
        "name": "RVU Temp Probe 4",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x010B: {
        "key": "fan1_speed_rpm",
        "name": "Fan 1 Speed RPM",
        "unit": "rpm",
        "readable": True,
    },
    0x010C: {
        "key": "fan2_speed_rpm",
        "name": "Fan 2 Speed RPM",
        "unit": "rpm",
        "readable": True,
    },
    0x010D: {
        "key": "fan1_speed_percent",
        "name": "Fan 1 Duty %",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        "readable": True,
    },
    0x010E: {
        "key": "fan2_speed_percent",
        "name": "Fan 2 Duty %",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        "readable": True,
    },
    0x010F: {
        "key": "preheater_percent",
        "name": "Preheater Duty %",
        "unit": "%",
        "readable": True,
    },
    0x0106: {
        "key": "humidity_setpoint",
        "name": "Humidity Setpoint",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        "device_class": "humidity",
        "readable": True,
    },
    0x0113: {
        "key": "co2_level",
        "name": "CO2 Level",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "device_class": "carbon_dioxide",
        "readable": True,
    },
    0x0119: {
        "key": "operation_mode",
        "name": "RVU Operating Mode",
        "readable": True,
    },
    0x011A: {
        "key": "party_mode_status",
        "name": "Party Mode Status",
        "readable": True,
    },
    0x0107: {
        "key": "filter_alarm",
        "name": "Filter Alarm",
        "readable": True,
    },
}


REGISTER_DEFINITIONS = {
    # ... (your original register definitions, as provided above)
    0x0213: {
        "key": "speed_1_pct",
        "name": "1st speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 0,
        "max": 35,
        "readable": True,
        "writable": True,
    },
    0x0214: {
        "key": "speed_2_pct",
        "name": "2nd speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 35,
        "max": 70,
        "readable": True,
        "writable": True,
    },
    0x0215: {
        "key": "speed_3_pct",
        "name": "3rd speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 45,
        "max": 100,
        "readable": True,
        "writable": True,
    },
    0x0216: {
        "key": "speed_4_pct",
        "name": "4th speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 100,
        "max": 110,
        "readable": True,
        "writable": True,
    },
    0x0217: {
        "key": "speed_boost_pct",
        "name": "Boost Speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 110,
        "max": 130,
        "readable": True,
        "writable": True,
    },
    0x0218: {
        "key": "temp_summer_set",
        "name": "Summer T Setpoint",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 300,
        "readable": True,
        "writable": True,
    },
    0x0219: {
        "key": "temp_winter_set",
        "name": "Winter T Setpoint",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 300,
        "readable": True,
        "writable": True,
    },
    0x021A: {
        "key": "air_coeff_recalc_interval",
        "name": "Air Coefficients Recalc. Interval",
        "unit": "min",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 15,
        "readable": True,
        "writable": True,
    },
    0x021B: {
        "key": "temp_free_cooling",
        "name": "Temp for Free Cooling",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 300,
        "readable": True,
        "writable": True,
    },
    0x021C: {
        "key": "temp_free_heating",
        "name": "Temp for Free Heating",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 300,
        "readable": True,
        "writable": True,
    },
    0x021D: {
        "key": "fan2_unbalance_pct",
        "name": "Fan 2 Unbalance %",
        "unit": "%",
        "scale": 1,
        "precision": 0,
        "min": -20,
        "max": 20,
        "readable": True,
        "writable": True,
    },
    0x021E: {
        "key": "humidity_samples",
        "name": "Humidity Samples for Setpoint",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 96,
        "readable": True,
        "writable": True,
    },
    0x021F: {
        "key": "boost_time",
        "name": "Boost Time",
        "unit": "min",
        "scale": 1,
        "precision": 0,
        "min": 60,
        "max": 240,
        "readable": True,
        "writable": True,
    },
    0x0220: {
        "key": "hum_reg_p_const",
        "name": "Humidity P Constant",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 5,
        "max": 50,
        "readable": True,
        "writable": True,
    },
    0x0221: {
        "key": "filter_life",
        "name": "Filter Life",
        "unit": "Days",
        "scale": 1,
        "precision": 0,
        "min": 30,
        "max": 400,
        "readable": True,
        "writable": True,
    },
    0x0222: {
        "key": "co2_min_set",
        "name": "CO2 PPM Min",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0223: {
        "key": "co2_nom_set",
        "name": "CO2 PPM Nom",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0224: {
        "key": "co2_max_set",
        "name": "CO2 PPM Max",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0225: {
        "key": "co2_prop_const",
        "name": "CO2 Prop Constant",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 10,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    0x0212: {
        "key": "manual_speed_level",
        "name": "Manual Speed Level",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {
            1: "Speed 1",
            2: "Speed 2",
            3: "Speed 3",
            4: "Speed 4"
        }
    },
    0x0306: {
        "key": "timer_program",
        "name": "Timer Program",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {
            1: "Program 1 (Fixed)",
            2: "Program 2 (Fixed)",
            3: "Program 3 (Fixed)",
            4: "Program 4 (Fixed)",
            5: "Program 5 (Manual)",
            6: "Program 6 (Manual)",
            7: "Program 7 (Manual)",
            8: "Program 8 (Manual)"
        }
    },
    0x0307: {
        "key": "mode_selection",
        "name": "Operating Mode",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {
            0: "Manual",
            1: "Auto",
            2: "Program",
            3: "Holiday",
            4: "Party"
        }
    },
}

# Number definitions, generated from REGISTER_DEFINITIONS
NUMBER_DEFINITIONS = [
    {
        "address": addr,
        "key": reg["key"],
        "name": reg["name"],
        "min": reg["min"],
        "max": reg["max"],
        "unit": reg["unit"],
        "scale": reg.get("scale", 1),
        "precision": reg.get("precision", 0),
        "unique_id": f"sabiana_number_{reg['key']}",
    }
    for addr, reg in REGISTER_DEFINITIONS.items()
    if reg.get("writable") and not reg.get("options")

]

# Example for select definitions (fill as needed)
SELECT_DEFINITIONS = [
    # {
    #     "address": 0x0300,
    #     "name": "Operation Mode",
    #     "options": ["Auto", "Manual", "Off"],
    #     "option_map": {0: "Auto", 1: "Manual", 2: "Off"},
    #     "unique_id": "sabiana_select_operation_mode",
    # },
]

# Diagnostic definitions (for binary_sensor.py)
DIAGNOSTIC_DEFINITIONS = {
    0x0104: {
        "type": "uint16",
        "bits": {
            0: {"key": "cfg_inverted", "name": "Config Inverted"},
            1: {"key": "cfg_preheating", "name": "Preheating Present"},
            2: {"key": "cfg_preheating_h2o", "name": "Preheating with Water"},
            3: {"key": "cfg_post_treatment", "name": "Post Treatment ON"},
            4: {"key": "cfg_post_summer", "name": "Post Treatment Summer"},
            5: {"key": "cfg_rl5_iaq", "name": "Relay 5 IAQ or Fault"},
            6: {"key": "cfg_pre_treatment", "name": "Pre Treatment"},
            7: {"key": "cfg_boiler_pboost", "name": "Boiler Pressure Boost"},
            8: {"key": "cfg_post_ext_he", "name": "Post Treatment Ext. HE"},
            9: {"key": "cfg_uart_highspd", "name": "UART High Speed"},
        }
    },
    0x0105: {
        "type": "uint16",
        "bits": {
            0: {"key": "remote_off", "name": "Remote OFF Active"},
            1: {"key": "bypass_active", "name": "Bypass Active"},
            2: {"key": "elec_preheat_active", "name": "Electric Preheater Active"},
            3: {"key": "water_preheat_active", "name": "Water Preheater Active"},
            4: {"key": "boost_active", "name": "Boost Active"},
            5: {"key": "defrost_cycle_active", "name": "Defrost Cycle Active"},
            7: {"key": "party_mode_active", "name": "Party Mode Active"},
            8: {"key": "on_status", "name": "Unit ON"},
            11: {"key": "winter_setting", "name": "Winter Setting"},
        }
    },
    0x0109: {
        "type": "uint8",
        "bits": {
            0: {"key": "relay_iaq_fault", "name": "IAQ Fault Relay ON"},
            1: {"key": "relay_preheat", "name": "Preheat Relay ON"},
            2: {"key": "relay_postheat", "name": "Postheat Relay ON"},
            3: {"key": "relay_fans", "name": "Fans Relay ON"},
            4: {"key": "relay_postcool", "name": "Postcool/Heat2 Relay ON"},
        }
    }
}

FIRMWARE_INFO = {
    0x0000: {
        "key": "device_serial_number",
        "name": "Serial Number",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "char",
        "dataLength": 20,
        "readable": True,
        "writable": False,
    },
    0x000A: {
        "key": "controller_model",
        "name": "Contoller Model",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000B: {
        "key": "firmware_release",
        "name": "Firmware Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000C: {
        "key": "protocol_release",
        "name": "Protocol Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000D: {
        "key": "tep_release",
        "name": "TEP Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
}
def get_device_info(entry_id: str):
    return {
        "identifiers": {(DOMAIN, entry_id)},
        "name": "Sabiana RVU",
        "manufacturer": "Sabiana",
        "model": "Smart Pro"
    }