import logging
from homeassistant.helpers.entity import EntityCategory

DOMAIN = "sabiana_energy_smart"
CONF_SLAVE = "slave"

LOGGER = logging.getLogger(__package__)

# SENSOR_DEFINITIONS = [
#     {"name": "RVU Temp Probe 1", "address": 0x0100, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp1"},
#     {"name": "RVU Temp Probe 2", "address": 0x0101, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp2"},
#     {"name": "RVU Temp Probe 3", "address": 0x0102, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp3"},
#     {"name": "RVU Temp Probe 4", "address": 0x0103, "unit": "°C", "scale": 0.1, "precision": 1, "device_class": "temperature", "unique_id": "sabiana_sensor_probe_temp4"},
#     {"name": "Fan 1 Speed RPM", "address": 0x010B, "unit": "rpm", "unique_id": "sabiana_sensor_fan1_speed_rpm"},
#     {"name": "Fan 2 Speed RPM", "address": 0x010C, "unit": "rpm", "unique_id": "sabiana_sensor_fan2_speed_rpm"},
#     {"name": "Fan 1 Duty %", "address": 0x010D, "unit": "%", "scale": 0.1, "precision": 1, "unique_id": "sabiana_sensor_fan1_speed_percent"},
#     {"name": "Fan 2 Duty %", "address": 0x010E, "unit": "%", "scale": 0.1, "precision": 1, "unique_id": "sabiana_sensor_fan2_speed_percent"},
#     {"name": "Preheater Duty %", "address": 0x010F, "unit": "%", "unique_id": "sabiana_sensor_preaheter_percent"},
#     {"name": "Humidity Setpoint", "address": 0x0106, "unit": "%", "scale": 0.1, "precision": 1, "device_class": "humidity", "unique_id": "sabiana_sensor_humidity_setpoin"},
#     {"name": "CO2 Level", "address": 0x0113, "unit": "ppm", "scale": 0.01, "precision": 2, "device_class": "carbon_dioxide", "unique_id": "sabiana_sensor_co2_level"},
#     {"name": "RVU Operating Mode", "address": 0x0119, "unique_id": "sabiana_sensor_operation_mode"},
#     {"name": "Party Mode Status", "address": 0x011A, "unique_id": "sabiana_sensor_partymode"},
#     {"name": "Filter Alarm", "address": 0x0107, "unique_id": "sabiana_sensor_filter_alarm"},
# ]

SENSOR_DEFINITIONS_NEW = {
    0x0100: {
        "key": "probe_temp1",
        "name": "External air temperature probe (T1)",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0101: {
        "key": "probe_temp2",
        "name": "Intake air temperature probe (T2)",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0102: {
        "key": "probe_temp3",
        "name": "Stale extracted air temperature probe (T3)",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0103: {
        "key": "probe_temp4",
        "name": "Exhaust air temperature probe (T4)",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x0106: {
        "key": "humidity_setpoint",
        "name": "Humidity Setpoint",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        "device_class": "humidity",
        "readable": True,
    },
    0x0107: {
        "key": "filter_alarm",
        "name": "Filter counter",
        "readable": True,
    },
    0x010B: {
        "key": "fan1_speed_rpm",
        "name": "Fan 1 Speed RPM (rd2)",
        "unit": "rpm",
        "readable": True,
    },
    0x010C: {
        "key": "fan2_speed_rpm",
        "name": "Fan 2 Speed RPM (rd2)",
        "unit": "rpm",
        "readable": True,
    },
    0x010D: {
        "key": "fan1_speed_percent",
        "name": "Fan 1 Duty (rd1)",
        "unit": "%",
        "scale": 0.01,
        "precision": 1,
        "readable": True,
    },
    0x010E: {
        "key": "fan2_speed_percent",
        "name": "Fan 2 Duty (rd1)",
        "unit": "%",
        "scale": 0.01,
        "precision": 1,
        "readable": True,
    },
    0x010F: {
        "key": "preheater_percent",
        "name": "Preheater Duty %",
        "unit": "%",
        "readable": True,
    },
    0x0111: {
        "key": "PressDiffSensor1",
        "name": "Diff. Pressure Sensor 1",
        "unit": "Pa",
        "scale": 0.1,
        "precision": 2,
        # "device_class": "carbon_dioxide",
        "readable": True,
    },
    0x0112: {
        "key": "PressDiffSensor2",
        "name": "Diff. Pressure Sensor 2",
        "unit": "Pa",
        "scale": 0.1,
        "precision": 2,
        # "device_class": "carbon_dioxide",
        "readable": True,
    },
    0x0113: {
        "key": "co2_level",
        "name": "CO2 Level",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "device_class": "carbon_dioxide",
        "readable": True,
    },
    0x0115: {
        "key": "Rho1",
        "name": "Rho1 - V1 In (kg/m3)",
        "unit": "kg/m3",
        "scale": 0.1,
        "precision": 1,
        "type": "float32",
        # "device_class": "humidity",
        "readable": True,
    },
    0x0117: {
        "key": "Rho2",
        "name": "Rho2 - V1 Out (kg/m3)",
        "unit": "kg/m3",
        "scale": 0.1,
        "precision": 1,
        "type": "float32",
        # "device_class": "humidity",
        "readable": True,
    },
    0x0119: {
        "key": "Rho3",
        "name": "Rho3 - V2 In (kg/m3)",
        "unit": "kg/m3",
        "scale": 0.1,
        "precision": 1,
        "type": "float32",
        # "device_class": "humidity",
        "readable": True,
    },
    0x011B: {
        "key": "Rho4",
        "name": "Rho4 - V2 Out (kg/m3)",
        "unit": "kg/m3",
        "scale": 0.1,
        "precision": 1,
        "type": "float32",
        # "device_class": "humidity",
        "readable": True,
    },
    0x011D: {
        "key": "SpeedCoeff1",
        "name": "Speed coeff. 1",
        "readable": True,
    },
    0x011E: {
        "key": "SpeedCoeff2",
        "name": "Speed coeff. 2",
        "readable": True,
    },
    0x0120: {
        "key": "FanOnHrs",
        "name": "Fans ON hours counter",
        "unit": "hours",
        "scale": 1,
        "precision": 0,
        "readable": True,
    },
}


REGISTER_DEFINITIONS = {
    # 0x0000: {
    #     "key": "device_serial_number",
    #     "name": "Serial Number",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "type": "char",
    #     "dataLength": 20,
    #     "readable": True,
    #     "writable": False,
    # },
    # 0x000A: {
    #     "key": "controller_model",
    #     "name": "Contoller Model",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "type": "uns16",
    #     "dataLength": 2,
    #     "readable": True,
    #     "writable": False,
    # },
    # 0x000B: {
    #     "key": "firmware_release",
    #     "name": "Firmware Release",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "type": "uns16",
    #     "dataLength": 2,
    #     "readable": True,
    #     "writable": False,
    # },
    # 0x000C: {
    #     "key": "protocol_release",
    #     "name": "Protocol Release",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "type": "uns16",
    #     "dataLength": 2,
    #     "readable": True,
    #     "writable": False,
    # },
    # 0x000D: {
    #     "key": "tep_release",
    #     "name": "TEP Release",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "type": "uns16",
    #     "dataLength": 2,
    #     "readable": True,
    #     "writable": False,
    # },
    # ... (your original register definitions, as provided above)
    # Should be implemented but don't recomand to be used... Maybe should use only the read method bit for diagnose?
    # 0x0200: {
    #     "key": "speed_1_pct",
    #     "name": "1st speed %",
    #     "unit": "%",
    #     "device_class": "power_factor",
    #     "scale": 1,
    #     "precision": 0,
    #     "min": 0,
    #     "max": 35,
    #     "readable": True,
    #     "writable": True,
    # },
    0x0201: {
        "key": "TempProbe1Ofst",
        "name": "Temp. probe 1 offset",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": -40,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    0x0202: {
        "key": "TempProbe2Ofst",
        "name": "Temp. probe 2 offset",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": -40,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    0x0203: {
        "key": "TempProbe3Ofst",
        "name": "Temp. probe 3 offset",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": -40,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    0x0204: {
        "key": "TempProbe4Ofst",
        "name": "Temp. probe 4 offset",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": -40,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    0x0205: {
        "key": "FanVoltageMin",
        "name": "Fan min voltage",
        "unit": "mV",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 100,
        "max": 1000,
        "readable": True,
        "writable": True,
    },
    0x0206: {
        "key": "FanVoltageMax",
        "name": "Fan max voltage",
        "unit": "mV",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 100,
        "max": 1000,
        "readable": True,
        "writable": True,
    },
    0x0207: {
        "key": "Fan1VoltageNom",
        "name": "Fan 1 Nominal V drive",
        "unit": "mV",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 100,
        "max": 1000,
        "readable": True,
        "writable": True,
    },
    0x0208: {
        "key": "Fan2VoltageNom",
        "name": "Fan 2 Nominal V drive",
        "unit": "mV",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 100,
        "max": 1000,
        "readable": True,
        "writable": True,
    },
    0x0209: {
        "key": "FanMinSpeed",
        "name": "Fan min speed",
        "unit": "rpm",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 200,
        "max": 4000,
        "readable": True,
        "writable": True,
    },
    0x020A: {
        "key": "FanMaxSpeed",
        "name": "Fan max speed",
        "unit": "rpm",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 1000,
        "max": 4000,
        "readable": True,
        "writable": True,
    },
    0x020B: {
        "key": "Fan1SpeedSet",
        "name": "Fan 1 nominal speed",
        "unit": "rpm",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 1000,
        "max": 4000,
        "readable": True,
        "writable": True,
    },
    0x020C: {
        "key": "Fan2SpeedSet",
        "name": "Fan 2 nominal speed",
        "unit": "rpm",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 1000,
        "max": 4000,
        "readable": True,
        "writable": True,
    },
    0x020D: {
        "key": "Fan1SpeedStd",
        "name": "Fan 1 installation speed",
        "unit": "rpm",
        # "device_class": "temperature",
        # "scale": 0.1,
        "precision": 0,
        "min": 1000,
        "max": 4000,
        "readable": True,
        "writable": True,
    },
    0x020E: {
        "key": "KCoeff1",
        "name": "K coefficient 1",
        "unit": "",
        "precision": 0,
        "min": 1000,
        "max": 9000,
        "readable": True,
        "writable": True,
    },
    0x020F: {
        "key": "KCoeff2",
        "name": "K coefficient 2",
        "unit": "",
        "precision": 0,
        "min": 1000,
        "max": 9000,
        "readable": True,
        "writable": True,
    },
    0x0210: {
        "key": "AirFlow1",
        "name": "Air flow 1",
        "unit": "m3/h",
        "precision": 0,
        "min": 30,
        "max": 500,
        "readable": True,
        "writable": True,
    },
    0x0211: {
        "key": "AirFlow2",
        "name": "Air flow 2",
        "unit": "m3/h",
        "precision": 0,
        "min": 30,
        "max": 500,
        "readable": True,
        "writable": True,
    },
    0x0213: {
        "key": "speed_1_pct",
        "name": "1st speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 0,
        "max": 35,
        "readable": True,
        "writable": True,
    },
    0x0214: {
        "key": "speed_2_pct",
        "name": "2nd speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 35,
        "max": 70,
        "readable": True,
        "writable": True,
    },
    0x0215: {
        "key": "speed_3_pct",
        "name": "3rd speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 45,
        "max": 100,
        "readable": True,
        "writable": True,
    },
    0x0216: {
        "key": "speed_4_pct",
        "name": "4th speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 100,
        "max": 110,
        "readable": True,
        "writable": True,
    },
    0x0217: {
        "key": "speed_boost_pct",
        "name": "Boost Speed %",
        "unit": "%",
        "device_class": "power_factor",
        "scale": 1,
        "precision": 0,
        "min": 110,
        "max": 130,
        "readable": True,
        "writable": True,
    },
    0x0218: {
        "key": "temp_summer_set",
        "name": "Summer T Setpoint",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": 10,
        "max": 30,
        "readable": True,
        "writable": True,
        # TODO: Should be multiplid with the scale factor, which is 0.1?
    },
    0x0219: {
        "key": "temp_winter_set",
        "name": "Winter T Setpoint",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": 10,
        "max": 30,
        "readable": True,
        "writable": True,
    },
    0x021A: {
        "key": "air_coeff_recalc_interval",
        "name": "Air Coefficients Recalc. Interval",
        "unit": "min",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 15,
        "readable": True,
        "writable": True,
    },
    0x021B: {
        "key": "temp_free_cooling",
        "name": "Temp for Free Cooling",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": 10,
        "max": 30,
        "readable": True,
        "writable": True,
    },
    0x021C: {
        "key": "temp_free_heating",
        "name": "Temp for Free Heating",
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "precision": 2,
        "min": 10,
        "max": 30,
        "readable": True,
        "writable": True,
    },
    0x021D: {
        "key": "fan2_unbalance_pct",
        "name": "Fan 2 Unbalance %",
        "unit": "%",
        "scale": 1,
        "precision": 0,
        "min": -20,
        "max": 20,
        "readable": True,
        "writable": True,
    },
    0x021E: {
        "key": "humidity_samples",
        "name": "Humidity Samples for Setpoint",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 96,
        "readable": True,
        "writable": True,
    },
    0x021F: {
        "key": "boost_time",
        "name": "Boost Time",
        "unit": "min",
        "scale": 1,
        "precision": 0,
        "min": 60,
        "max": 240,
        "readable": True,
        "writable": True,
    },
    0x0220: {
        "key": "hum_reg_p_const",
        "name": "Humidity P Constant",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 5,
        "max": 50,
        "readable": True,
        "writable": True,
    },
    0x0221: {
        "key": "filter_life",
        "name": "Filter Life",
        "unit": "Days",
        "scale": 1,
        "precision": 0,
        "min": 30,
        "max": 400,
        "readable": True,
        "writable": True,
    },
    0x0222: {
        "key": "co2_min_set",
        "name": "CO2 PPM Min",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0223: {
        "key": "co2_nom_set",
        "name": "CO2 PPM Nom",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0224: {
        "key": "co2_max_set",
        "name": "CO2 PPM Max",
        "unit": "ppm",
        "scale": 0.01,
        "precision": 2,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0225: {
        "key": "co2_prop_const",
        "name": "CO2 Prop Constant",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 10,
        "max": 40,
        "readable": True,
        "writable": True,
    },
    # TODO: Bit Mod for 0x226
    # Its a range... how is this set up? TODO: See and fix.
    0x0227: {
        "key": "CO2SensorRange",
        "name": "CO2 Sensor PPM Range",
        "unit": "ppm",
        "precision": 0,
        "min": 100,
        "max": 30000,
        "readable": True,
        "writable": True,
    },
    0x0228: {
        "key": "BoilerBoostTime",
        "name": "Boiler boost time",
        "unit": "Minutes",
        "scale": 1,
        "precision": 0,
        "min": 5,
        "max": 20,
        "readable": True,
        "writable": True,
    },
    0x0229: {
        "key": "RelHumLowSet",
        "name": "RH Low value",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        # "min": 200,
        # "max": 300,
        "min": 20,
        "max": 30,
        "readable": True,
        "writable": True,
    },
    0x022A: {
        "key": "RelHumStdSet",
        "name": "RH Standard value",
        "unit": "%",
        "scale": 0.1,
        "precision": 1,
        # "min": 400,
        # "max": 600,
        "min": 40,
        "max": 60,
        "readable": True,
        "writable": True,
    },
    0x022B: {
        "key": "RelHumHiSet",
        "name": "RH Hi value",
        "unit": "%",
        "scale": 0.1,
        "precision": 2,
        # "min": 600,
        # "max": 800,
        "min": 60,
        "max": 80,
        "readable": True,
        "writable": True,
    },
    # 0x0210: {
    #     "key": "",
    #     "name": "",
    #     "unit": "",
    #     "scale": 1,
    #     "precision": 0,
    #     "min": ,
    #     "max": ,
    #     "readable": True,
    #     "writable": True,
    # },
}

SWITCH_DEFINITIONS = {
    0x0300: {
        "key": "CMD_OnOff",
        "name": "Power On/Off",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "switch",
    },
}
BUTTON_DEFINITIONS = {
    0x0301: {
        "key": "CMD_Manual",
        "name": "Manual mode",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0302: {
        "key": "CMD_Holiday",
        "name": "Holiday mode",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0303: {
        "key": "CMD_Party",
        "name": "Party mode",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0304: {
        "key": "CMD_Auto",
        "name": "Auto mode",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0305: {
        "key": "CMD_Program",
        "name": "Program mode",
        "unit": "",
        "device_class": "power",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
}
# Number definitions, generated from REGISTER_DEFINITIONS
NUMBER_DEFINITIONS = [
    {
        "address": addr,
        "key": reg["key"],
        "name": reg["name"],
        "min": reg.get("min", 0),
        "max": reg.get("max", 0),
        "unit": reg.get("unit", ""),
        "scale": reg.get("scale", 1),
        "precision": reg.get("precision", 0),
        "unique_id": f"sabiana_number_{reg['key']}",
    }
    for addr, reg in REGISTER_DEFINITIONS.items()
    if reg.get("writable")
]

# Example for select definitions (fill as needed)
SELECT_DEFINITIONS = {
    0x0212: {
        "key": "manual_speed_level",
        "name": "Manual Speed Level",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {0: "Speed 1", 1: "Speed 2", 2: "Speed 3", 3: "Speed 4"},
    },
    0x0306: {
        "key": "timer_program",
        "name": "Timer Program",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {
            1: "Program 1 (Fixed)",
            2: "Program 2 (Fixed)",
            3: "Program 3 (Fixed)",
            4: "Program 4 (Fixed)",
            5: "Program 5 (Manual)",
            6: "Program 6 (Manual)",
            7: "Program 7 (Manual)",
            8: "Program 8 (Manual)",
        },
    },
    0x0307: {
        "key": "mode_selection",
        "name": "Operating Mode",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {0: "Holiday", 1: "Auto", 2: "Program", 3: "Manual", 4: "Party"},
    },
}

# Diagnostic definitions (for binary_sensor.py)
DIAGNOSTIC_DEFINITIONS = {
    0x0104: {
        "type": "uint16",
        "entity_category": None,  # EntityCategory.NONE,
        # EntityCategory.NONE,
        "bits": {
            0: {"key": "cfg_inverted", "name": "Config Inverted"},
            1: {"key": "cfg_preheating", "name": "Preheating Present"},
            2: {"key": "cfg_preheating_h2o", "name": "Preheating with Water"},
            3: {"key": "cfg_post_treatment", "name": "Post Treatment ON"},
            4: {"key": "cfg_post_summer", "name": "Post Treatment Summer"},
            5: {"key": "cfg_rl5_iaq", "name": "Relay 5 IAQ or Fault"},
            6: {"key": "cfg_pre_treatment", "name": "Pre Treatment"},
            7: {"key": "cfg_boiler_pboost", "name": "Boiler Pressure Boost"},
            8: {"key": "cfg_post_ext_he", "name": "Post Treatment Ext. HE"},
            9: {"key": "cfg_uart_highspd", "name": "UART High Speed"},
            10: {"key": "cfg_post_treatment_T3/T2", "name": "Post treatment T3/T2"},
        },
    },
    0x0105: {
        "type": "uint16",
        "entity_category": None,
        # "entity_category": EntityCategory.CONFIG,
        "bits": {
            0: {"key": "remote_off", "name": "Remote OFF Active"},
            1: {"key": "bypass_active", "name": "Bypass Active"},
            2: {"key": "elec_preheat_active", "name": "Electric Preheater Active"},
            3: {"key": "water_preheat_active", "name": "Water Preheater Active"},
            4: {"key": "boost_active", "name": "Boost Active"},
            5: {"key": "defrost_cycle_active", "name": "Defrost Cycle Active"},
            7: {"key": "party_mode_active", "name": "Party Mode Active"},
            8: {"key": "on_status", "name": "Unit ON"},
            11: {"key": "winter_setting", "name": "Winter Setting"},
        },
    },
    0x0108: {
        "type": "uint16",
        # "entity_category": EntityCategory.CONFIG,
        "entity_category": None,
        "bits": {
            2: {"key": "OUT_Damper_CW", "name": "Damper CW output"},
            3: {"key": "OUT_Damper_CCW", "name": "Damper CCW output"},
        },
    },
    0x0109: {
        "type": "uint8",
        # "entity_category": EntityCategory.CONFIG,
        "entity_category": None,
        "bits": {
            0: {"key": "relay_iaq_fault", "name": "IAQ Fault Relay ON"},
            1: {"key": "relay_preheat", "name": "Preheat Relay ON"},
            2: {"key": "relay_postheat", "name": "Postheat Relay ON"},
            3: {"key": "relay_fans", "name": "Fans Relay ON"},
            4: {"key": "relay_postcool", "name": "Postcool/Heat2 Relay ON"},
        },
    },
    0x010A: {
        "type": "uint8",
        # "entity_category": EntityCategory.CONFIG,
        "entity_category": None,
        "bits": {
            1: {"key": "DIN_C1", "name": "Input C1 status"},
            2: {"key": "DIN_C2", "name": "Input C2 status"},
            3: {"key": "DIN_C3", "name": "Input C3 status"},
            4: {"key": "DIN_C4", "name": "Input C4 status"},
        },
    },
    0x0110: {
        "type": "uint16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "bits": {
            0: {"key": "ALM_T1_Fail", "name": "T1 probe failure alarm"},
            1: {"key": "ALM_T2_Fail", "name": "T2 probe failure alarm"},
            2: {"key": "ALM_T3_Fail", "name": "T3 probe failure alarm"},
            3: {"key": "ALM_T4_Fail", "name": "T4 probe failure alarm"},
            4: {"key": "ALM_Timekeeper", "name": "Timekeeper failure alarm"},
            5: {"key": "ALM_Frost", "name": "Frost alarm"},
            6: {"key": "ALM_Frost_T2", "name": "Frost alarm (from T2 probe)"},
            7: {"key": "ALM_Fireplace", "name": "Fireplace Alarm"},
            8: {"key": "ALM_PressTxFail", "name": "Pressure transducer failure alarm"},
            9: {"key": "ALM_Filter", "name": "Filter alarm"},
            10: {"key": "ALM_FansFail", "name": "Fans failure"},
            11: {"key": "ALM_RH_CO2_TxFail", "name": "RH or CO2 sensor failure alarm"},
            12: {"key": "ALM_FanThermalInput", "name": "Fan thermic input alarm"},
            14: {"key": "ALM_PreHeating", "name": "Pre Heating alarm"},
            15: {"key": "ALM_PreFrost_T2", "name": "Pre frost alarm (T2)"},
        },
    },
    0x011F: {
        "type": "uint16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "bits": {
            8: {"key": "OPT_IAQ", "name": "IAQ Used"},
            9: {"key": "OPT_PostTreatment", "name": "Post treatment used"},
            10: {"key": "OPT_HE", "name": "HE used"},
            11: {"key": "OPT_BoilerBoost", "name": "Boiler boost mode used"},
            12: {"key": "OPT_CO2Sensor", "name": "CO2 sensor present"},
            13: {
                "key": "OPT_DiffPressSensor",
                "name": "Differential pressure sensor present",
            },
            14: {"key": "OPT_RHSensor", "name": "RH sensor present"},
            15: {"key": "OPT_ReverseMount", "name": "Reverse mounting"},
        },
    },
    # is read write but maybe we should not touch it.
    0x0200: {
        "type": "sig16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "bits": {
            1: {"key": "S_PRM_StopFanOn", "name": "Stop Mode Fan status"},
            2: {"key": "S_PRM_FlushFanOn", "name": "Flush Fan status"},
        },
    },
}

FIRMWARE_INFO = {
    0x0000: {
        "key": "device_serial_number",
        "name": "Serial Number",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "char",
        "dataLength": 20,
        "readable": True,
        "writable": False,
    },
    0x000A: {
        "key": "controller_model",
        "name": "Contoller Model",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000B: {
        "key": "firmware_release",
        "name": "Firmware Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000C: {
        "key": "protocol_release",
        "name": "Protocol Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x000D: {
        "key": "tep_release",
        "name": "TEP Release",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
}


def get_device_info(entry_id: str):
    return {
        "identifiers": {(DOMAIN, entry_id)},
        "name": "Sabiana RVU",
        "manufacturer": "Sabiana",
        "model": "Smart Pro",
    }
